# EDA

In [61]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.

c:\Users\vkessori\Desktop\Data Fullstack\10_Final_project\skinmatch\.venv\Scripts\python.exe: No module named pip

In [62]:
import pandas as pd

In [63]:
df = pd.read_csv("skincare.csv")
df

,Unnamed: 0,Title,Product,Category,Brand,Skin_Type,Number of items,Sold By,Price,Link
0,0,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,SKINCARE,Nivea,All,1,AIR SALES,372,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,1,"Nivea Soft Playful Peach, Light Moistu...",Moisturizer,SKINCARE,Nivea,All,1,RK World Infocom Pvt Ltd,226,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,2,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,SKINCARE,Nivea,Dry,1,MURALI RETAILS,103,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,3,Biotique Morning Nectar Flawless Skin ...,Moisturizer,SKINCARE,Biotique,Combination,1,RK World Infocom Pvt Ltd,240,https://www.amazon.in/Biotique-Morning-Nectar-...
4,4,Minimalist Marula Oil 5% Face Moisturi...,Moisturizer,SKINCARE,Minimalist,Dry,1,Minimalist Inc,284,https://www.amazon.in/Minimalist-Moisturizer-H...
...,...,...,...,...,...,...,...,...,...,...
1433,1433,PAVITYAKSH Saloon Express Stamping Pro...,Nail paint,SKINCARE,PAVITYAKSH,All,1,PAVITYAKSH,246,https://www.amazon.in/PAVITYAKSH-Saloon-Expres...
1434,1434,"JUICE Quick-dry, 100% Veg & Cruelty Fr...",Nail paint,SKINCARE,JUICE,All,1,JK Lifestyle Pvt Ltd.,320,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1435,1435,"JUICE Quick-dry, Nail Paint, Long Last...",Nail paint,SKINCARE,JUICE,All,1,JK Lifestyle Pvt Ltd.,199,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1436,1436,"BAD COMPANY No Toxin Nail Lacquer, Lon...",Nail paint,SKINCARE,BAD COMPANY,All,1,NaN,199,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1437,1437,Gleevia Reflective Glitter Color Disco...,Nail paint,SKINCARE,Gleevia,All,1,Gleevia Cosmetics,499,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [64]:
df.sample(10)

,Unnamed: 0,Title,Product,Category,Brand,Skin_Type,Number of items,Sold By,Price,Link
731,731,24K Gold Rose Water Facial Toner by Le...,Facial sprays,SKINCARE,Leven Rose,Oily,1,NaN,4320,https://www.amazon.in/Gold-Water-Facial-Toner-...
507,507,Random-mac Infallible Mattifying Base ...,Primer,SKINCARE,RANDOMMAC,Combination,1,KHATU SHYAM ENTERPRIS,198,https://www.amazon.in/Random-mac-Infallible-Ma...
306,306,LAKMÉ Absolute Blur Perfect Matte Face...,Primer,SKINCARE,LAKMÉ,All,1,Health&Glow,645,https://www.amazon.in/Lakme-Absolute-Perfect-M...
692,692,St.Botanica Hyaluronic Acid Hydra Boos...,Facial sprays,SKINCARE,St.Botanica,Normal,1,RK World Infocom Pvt Ltd,351,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
935,935,Vaseline Intensive Care Mature Skin Re...,Hand cream,SKINCARE,Vaseline,Dry,1,Venus.Enterprise,449,https://www.amazon.in/Vaseline-Intensive-Matur...
941,941,Neutrogena Concentrated Non Scented Ha...,Hand cream,SKINCARE,Neutrogena,Dry,1,Venus.Enterprise,530,https://www.amazon.in/Neutrogena-Concentrated-...
3,3,Biotique Morning Nectar Flawless Skin ...,Moisturizer,SKINCARE,Biotique,Combination,1,RK World Infocom Pvt Ltd,240,https://www.amazon.in/Biotique-Morning-Nectar-...
420,420,Maliao Star Ocean Illumine Primer Colo...,Primer,SKINCARE,Generic,All,1,Bajaj beauty,299,https://www.amazon.in/Maliao-Illumine-Primer-C...
968,968,Kimirica Hand Creams Combo gifting | M...,Hand cream,SKINCARE,Kimirica,All,1,RK World Infocom Pvt Ltd,932,https://www.amazon.in/Kimirica-Holiday-Smells-...
212,212,Aquasoft Fc Moisturizer cream with Vit...,Moisturizer,SKINCARE,Aquasoft,All,1,PAVIKA,340,https://www.amazon.in/Aquasoft-Moisturizer-cre...

In [65]:
df["Product"].value_counts()

Product
Nail paint       299
Moisturizer      289
Primer           289
Facial sprays    282
Hand cream       279
Name: count, dtype: int64

In [66]:
df.isnull().sum()

Unnamed: 0           0
Title                0
Product              0
Category             0
Brand                0
Skin_Type            0
Number of items      0
Sold By            207
Price                0
Link                 0
dtype: int64

In [67]:
df["Skin_Type"].value_counts()

Skin_Type
All                                                    992
Normal                                                 102
Dry                                                     93
Combination                                             56
Sensitive                                               26
Oily                                                    22
All, Oily, Sensitive, Dry, Normal                       19
All, Oily, Combination, Sensitive, Dry                  14
All, Oily, Combination, Dry, Normal                     13
Oily, Combination, Dry, Normal                           9
All, Combination, Sensitive, Dry, Normal                 6
Oily, Combination, Sensitive, Dry, Normal                6
Sensitive, Dry                                           5
Acne Prone                                               5
Acne Prone Skin                                          5
All, Dry                                                 4
Acne Prone,All Skin Types                                4
Dry, Normal                                              3
Acne                                                     3
All, Oily, Combination, Sensitive, Normal                3
All Skin, Oily, Combination, Sensitive, Dry, Normal      3
All, Oily, Dry, Normal                                   3
All, Acne                                                2
Normal to Oily Skin                                      2
Oily, Combination, Sensitive                             2
All, Oily                                                2
All, Acne Prone Skin, Combination, Sensitive, Dry        2
Oily, Combination, Dry                                   2
All, Combination, Dry                                    2
Oily, Acne Prone                                         1
Oily, Acne Prone, Sensitive                              1
Dry, Normal Skin                                         1
Normal to Dry skin                                       1
Oily, Combination                                        1
All, Sensitive                                           1
Dry;Combination                                          1
All, especially extra-dry skin                           1
Acne, Dry                                                1
All, Combination, Normal                                 1
All, Oily, Combination, Acne Prone, Dry, Normal          1
All Skin Types,Oily                                      1
All Skin Type                                            1
Acne Prone,Oily,Dry,All Skin Types                       1
Dry,All Skin Types                                       1
Oily, Combination, Sensitive, Dry                        1
Revitalized                                              1
All, Oily, Acne Prone Skin, Sensitive, Dry               1
Oily, Sensitive, Dry, Normal                             1
All, Oily, Acne Prone Skin, Sensitive                    1
Oily, Dry, Normal                                        1
All, Oily, Acne Prone Skin, Combination, Normal          1
All, Combination, Sensitive                              1
All, Oily, Acne Prone Skin, Combination, Sensitive       1
Dullness, Oily, Dry                                      1
All, Sensitive, Dry                                      1
Normal to Dry                                            1
Dull, Dehydrated, Cracked, Dry, Rough                    1
Name: count, dtype: int64

In [68]:
df.shape

(1438, 10)

In [69]:
df["Skin_Type"].nunique(dropna=False)

57

In [84]:
df["Skin_Type"].unique()

<ArrowStringArray>
[                                                'All',
                                                 'Dry',
                                         'Combination',
            'All, Combination, Sensitive, Dry, Normal',
                                              'Normal',
                                      'Sensitive, Dry',
                                    'Oily, Acne Prone',
                                         'Dry, Normal',
                                                'Acne',
                                                'Oily',
                         'Oily, Acne Prone, Sensitive',
                                           'All, Acne',
                                    'Dry, Normal Skin',
                                            'All, Dry',
                                           'Sensitive',
                      'Oily, Combination, Dry, Normal',
                                  'Normal to Dry skin',
           'All, Oily, Combination, Sensitive, Normal',
                                   'Oily, Combination',
                 'All, Oily, Combination, Dry, Normal',
                                      'All, Sensitive',
                                     'Dry;Combination',
                      'All, especially extra-dry skin',
                                 'Normal to Oily Skin',
                                           'Acne, Dry',
                            'All, Combination, Normal',
              'All, Oily, Combination, Sensitive, Dry',
                        'Oily, Combination, Sensitive',
     'All, Oily, Combination, Acne Prone, Dry, Normal',
                                 'All Skin Types,Oily',
                                       'All Skin Type',
                                          'Acne Prone',
                  'Acne Prone,Oily,Dry,All Skin Types',
                   'All, Oily, Sensitive, Dry, Normal',
 'All Skin, Oily, Combination, Sensitive, Dry, Normal',
                                  'Dry,All Skin Types',
                           'Acne Prone,All Skin Types',
           'Oily, Combination, Sensitive, Dry, Normal',
                                     'Acne Prone Skin',
                   'Oily, Combination, Sensitive, Dry',
                                         'Revitalized',
                                           'All, Oily',
          'All, Oily, Acne Prone Skin, Sensitive, Dry',
                        'Oily, Sensitive, Dry, Normal',
               'All, Oily, Acne Prone Skin, Sensitive',
   'All, Acne Prone Skin, Combination, Sensitive, Dry',
                              'Oily, Combination, Dry',
                                   'Oily, Dry, Normal',
                               'All, Combination, Dry',
     'All, Oily, Acne Prone Skin, Combination, Normal',
                         'All, Combination, Sensitive',
  'All, Oily, Acne Prone Skin, Combination, Sensitive',
                              'All, Oily, Dry, Normal',
                                 'Dullness, Oily, Dry']
Length: 54, dtype: str

## Nettoyage

In [71]:
# On droppe la colonne "Unnamed"

df_drop_col_unnamed = df.drop("Unnamed: 0", axis=1, inplace=True)

In [72]:
df

,Title,Product,Category,Brand,Skin_Type,Number of items,Sold By,Price,Link
0,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,SKINCARE,Nivea,All,1,AIR SALES,372,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,"Nivea Soft Playful Peach, Light Moistu...",Moisturizer,SKINCARE,Nivea,All,1,RK World Infocom Pvt Ltd,226,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,SKINCARE,Nivea,Dry,1,MURALI RETAILS,103,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Biotique Morning Nectar Flawless Skin ...,Moisturizer,SKINCARE,Biotique,Combination,1,RK World Infocom Pvt Ltd,240,https://www.amazon.in/Biotique-Morning-Nectar-...
4,Minimalist Marula Oil 5% Face Moisturi...,Moisturizer,SKINCARE,Minimalist,Dry,1,Minimalist Inc,284,https://www.amazon.in/Minimalist-Moisturizer-H...
...,...,...,...,...,...,...,...,...,...
1433,PAVITYAKSH Saloon Express Stamping Pro...,Nail paint,SKINCARE,PAVITYAKSH,All,1,PAVITYAKSH,246,https://www.amazon.in/PAVITYAKSH-Saloon-Expres...
1434,"JUICE Quick-dry, 100% Veg & Cruelty Fr...",Nail paint,SKINCARE,JUICE,All,1,JK Lifestyle Pvt Ltd.,320,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1435,"JUICE Quick-dry, Nail Paint, Long Last...",Nail paint,SKINCARE,JUICE,All,1,JK Lifestyle Pvt Ltd.,199,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1436,"BAD COMPANY No Toxin Nail Lacquer, Lon...",Nail paint,SKINCARE,BAD COMPANY,All,1,NaN,199,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1437,Gleevia Reflective Glitter Color Disco...,Nail paint,SKINCARE,Gleevia,All,1,Gleevia Cosmetics,499,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [73]:
# On exclut les lignes de produits de type "Manucure" et "Crème pour les mains" car pas concernées pour l'app

df = df[~df["Product"].isin(["Nail paint", "Hand cream"])]
df

,Title,Product,Category,Brand,Skin_Type,Number of items,Sold By,Price,Link
0,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,SKINCARE,Nivea,All,1,AIR SALES,372,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,"Nivea Soft Playful Peach, Light Moistu...",Moisturizer,SKINCARE,Nivea,All,1,RK World Infocom Pvt Ltd,226,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,SKINCARE,Nivea,Dry,1,MURALI RETAILS,103,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Biotique Morning Nectar Flawless Skin ...,Moisturizer,SKINCARE,Biotique,Combination,1,RK World Infocom Pvt Ltd,240,https://www.amazon.in/Biotique-Morning-Nectar-...
4,Minimalist Marula Oil 5% Face Moisturi...,Moisturizer,SKINCARE,Minimalist,Dry,1,Minimalist Inc,284,https://www.amazon.in/Minimalist-Moisturizer-H...
...,...,...,...,...,...,...,...,...,...
855,evanhealy Heat of Summer HydroSoul Fac...,Facial sprays,SKINCARE,Evanhealy,All,1,NaN,6358,https://www.amazon.in/evanhealy-HydroSoul-Hydr...
856,"D'MOKSHA Wine Vine Face Toner, Face Mi...",Facial sprays,SKINCARE,D'MOKSHA,Acne Prone Skin,10,NaN,300,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
857,Love Earth Jasmine Mogra Face Mist Ton...,Facial sprays,SKINCARE,Love Earth,All,1,LOVE EARTH,199,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
858,EcstaCBeauty Cure Skin Anti-Breakout F...,Facial sprays,SKINCARE,EcstaCBeauty,Sensitive,1,EcstaC Beauty,149,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
859,ISNTREE Green Tea Fresh Facial Toner O...,Facial sprays,SKINCARE,Isntree,Sensitive,1,VMKS India,1147,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [74]:
df["Product"].value_counts() # les lignes de produits "Hand cream" et "Nail paint" ont bien été masquées

Product
Moisturizer      289
Primer           289
Facial sprays    282
Name: count, dtype: int64

In [79]:
# On droppe la colonne "Category" car la valeur est la même sur toutes les lignes et n'apporte rien en termes d'infos
df.drop("Category", axis=1, inplace=True)

KeyError: "['Category'] not found in axis"

In [80]:
df

,Title,Product,Brand,Skin_Type,Number of items,Sold By,Price,Link
0,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,Nivea,All,1,AIR SALES,372,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,"Nivea Soft Playful Peach, Light Moistu...",Moisturizer,Nivea,All,1,RK World Infocom Pvt Ltd,226,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,Nivea,Dry,1,MURALI RETAILS,103,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Biotique Morning Nectar Flawless Skin ...,Moisturizer,Biotique,Combination,1,RK World Infocom Pvt Ltd,240,https://www.amazon.in/Biotique-Morning-Nectar-...
4,Minimalist Marula Oil 5% Face Moisturi...,Moisturizer,Minimalist,Dry,1,Minimalist Inc,284,https://www.amazon.in/Minimalist-Moisturizer-H...
...,...,...,...,...,...,...,...,...
855,evanhealy Heat of Summer HydroSoul Fac...,Facial sprays,Evanhealy,All,1,NaN,6358,https://www.amazon.in/evanhealy-HydroSoul-Hydr...
856,"D'MOKSHA Wine Vine Face Toner, Face Mi...",Facial sprays,D'MOKSHA,Acne Prone Skin,10,NaN,300,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
857,Love Earth Jasmine Mogra Face Mist Ton...,Facial sprays,Love Earth,All,1,LOVE EARTH,199,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
858,EcstaCBeauty Cure Skin Anti-Breakout F...,Facial sprays,EcstaCBeauty,Sensitive,1,EcstaC Beauty,149,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
859,ISNTREE Green Tea Fresh Facial Toner O...,Facial sprays,Isntree,Sensitive,1,VMKS India,1147,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [82]:
df["Brand"].value_counts()

Brand
Nivea         34
Generic       30
DEVIL MONK    22
LAKMÉ         18
Mamaearth     14
              ..
NOIANT         1
Evanhealy      1
D'MOKSHA       1
Love Earth     1
Isntree        1
Name: count, Length: 361, dtype: int64

In [85]:
# On supprime la colonne "Prix"

df = df.drop("Price", axis=1)

,Title,Product,Brand,Skin_Type,Number of items,Sold By,Link
0,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,Nivea,All,1,AIR SALES,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,"Nivea Soft Playful Peach, Light Moistu...",Moisturizer,Nivea,All,1,RK World Infocom Pvt Ltd,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,Nivea,Dry,1,MURALI RETAILS,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Biotique Morning Nectar Flawless Skin ...,Moisturizer,Biotique,Combination,1,RK World Infocom Pvt Ltd,https://www.amazon.in/Biotique-Morning-Nectar-...
4,Minimalist Marula Oil 5% Face Moisturi...,Moisturizer,Minimalist,Dry,1,Minimalist Inc,https://www.amazon.in/Minimalist-Moisturizer-H...
...,...,...,...,...,...,...,...
855,evanhealy Heat of Summer HydroSoul Fac...,Facial sprays,Evanhealy,All,1,NaN,https://www.amazon.in/evanhealy-HydroSoul-Hydr...
856,"D'MOKSHA Wine Vine Face Toner, Face Mi...",Facial sprays,D'MOKSHA,Acne Prone Skin,10,NaN,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
857,Love Earth Jasmine Mogra Face Mist Ton...,Facial sprays,Love Earth,All,1,LOVE EARTH,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
858,EcstaCBeauty Cure Skin Anti-Breakout F...,Facial sprays,EcstaCBeauty,Sensitive,1,EcstaC Beauty,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
859,ISNTREE Green Tea Fresh Facial Toner O...,Facial sprays,Isntree,Sensitive,1,VMKS India,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [ ]:
# la colonne "Number of items" n'est pas utile ici

df = df.drop("Number of items", axis=1)

In [93]:
df

,Title,Product,Brand,Skin_Type,Sold By,Link
0,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,Nivea,All,AIR SALES,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,"Nivea Soft Playful Peach, Light Moistu...",Moisturizer,Nivea,All,RK World Infocom Pvt Ltd,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,"Nivea Soft Light Moisturizer For Face,...",Moisturizer,Nivea,Dry,MURALI RETAILS,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Biotique Morning Nectar Flawless Skin ...,Moisturizer,Biotique,Combination,RK World Infocom Pvt Ltd,https://www.amazon.in/Biotique-Morning-Nectar-...
4,Minimalist Marula Oil 5% Face Moisturi...,Moisturizer,Minimalist,Dry,Minimalist Inc,https://www.amazon.in/Minimalist-Moisturizer-H...
...,...,...,...,...,...,...
855,evanhealy Heat of Summer HydroSoul Fac...,Facial sprays,Evanhealy,All,NaN,https://www.amazon.in/evanhealy-HydroSoul-Hydr...
856,"D'MOKSHA Wine Vine Face Toner, Face Mi...",Facial sprays,D'MOKSHA,Acne Prone Skin,NaN,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
857,Love Earth Jasmine Mogra Face Mist Ton...,Facial sprays,Love Earth,All,LOVE EARTH,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
858,EcstaCBeauty Cure Skin Anti-Breakout F...,Facial sprays,EcstaCBeauty,Sensitive,EcstaC Beauty,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
859,ISNTREE Green Tea Fresh Facial Toner O...,Facial sprays,Isntree,Sensitive,VMKS India,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...