# - Look Fantastic Skincare Products - 
# Analyse exploratoire des données

### Ce dataset présente des produits cosmétiques issus du site Look Fantastic et comprend des détails sur chaque produit : titre, type de produit, catégorie de produits, marque, type de peau, nombre d'items, nom du commerçant, son prix et le lien vers sa fiche produit.

### L'analyse de ce dataset s'inscrit dans le cadre du projet d'entraînement d'un modèle permettant de proposer des produits adaptés à des problématiques de peau après soumission d'une photo selfie par l'utilisateur.

## Import des données

In [35]:
import pandas as pd
df = pd.read_csv("skincare_products.csv")
df

,product_name,product_url,product_type,ingredients,price
0,The Ordinary Natural Moisturising Factors + HA...,https://www.lookfantastic.com/the-ordinary-nat...,Moisturiser,"Aqua (Water), Caprylic/Capric Triglyceride, Ce...",£5.20
1,CeraVe Facial Moisturising Lotion SPF 25 52ml,https://www.lookfantastic.com/cerave-facial-mo...,Moisturiser,"Aqua/Water, Homosalate, Glycerin, Octocrylene,...",£13.00
2,The Ordinary Hyaluronic Acid 2% + B5 Hydration...,https://www.lookfantastic.com/the-ordinary-hya...,Moisturiser,"Aqua (Water), Sodium Hyaluronate, Sodium Hyalu...",£6.20
3,AMELIORATE Transforming Body Lotion 200ml,https://www.lookfantastic.com/ameliorate-trans...,Moisturiser,"Aqua/Water/Eau, Ammonium Lactate, C12-15 Alkyl...",£22.50
4,CeraVe Moisturising Cream 454g,https://www.lookfantastic.com/cerave-moisturis...,Moisturiser,"Purified Water, Glycerin, Ceteareth-20 and Cet...",£16.00
...,...,...,...,...,...
1133,Elemis Life Elixirs Embrace Bath and Shower El...,https://www.lookfantastic.com/elemis-life-elix...,Bath Oil,"Prunus Amygdalus Dulcis (Sweet Almond) Oil, TI...",£55.00
1134,Love Boo Splendidly Soothing Bath Soak (250ml),https://www.lookfantastic.com/love-boo-splendi...,Bath Oil,"Aqua, sodium lauroyl sarcosinate, sodium cocoa...",£10.99
1135,Elemis Life Elixirs Fortitude Bath and Shower ...,https://www.lookfantastic.com/elemis-life-elix...,Bath Oil,"Prunus Amygdalus Dulcis (Sweet Almond) Oil, TI...",£55.00
1136,Connock London Kukui Oil Soothing Bath & Showe...,https://www.lookfantastic.com/connock-london-k...,Bath Oil,"Caprylic/Capric Triglyceride, PEG-40 Sorbitan ...",£36.00
1137,Weleda Baby Calendula Cream Bath (200ml),https://www.lookfantastic.com/weleda-baby-cale...,Bath Oil,"Water (Aqua), Prunis Amygdalus Dulcis (Sweet A...",£13.95

## Analyse générale du dataset

In [13]:
print("Nombre de lignes : ", df.shape[0])
print("Nombre de colonnes : ", df.shape[1])

Nombre de lignes :  1138
Nombre de colonnes :  5

In [24]:
# aperçu des 5 premières lignes
df.sample(5)

,product_name,product_url,product_type,ingredients,price
997,Sanctuary Spa Classic Body Wash 250ml,https://www.lookfantastic.com/sanctuary-spa-cl...,Body Wash,"Aqua (Water), Sodium Laureth Sulfate, Glycerin...",£6.00
1061,Aromatherapy Associates De-Stress Shower Oil 2...,https://www.lookfantastic.com/aromatherapy-ass...,Body Wash,"MIPA-Laureth Sulfate, Laureth-3, Caprylic/Capr...",£26.00
895,Avene Gentle Exfoliating Scrub 75ml,https://www.lookfantastic.com/avene-gentle-exf...,Exfoliator,"Avene Thermal Spring Water (Avene Aqua), Glyce...",£13.00
106,Clinique for Men Anti-Age Moisturiser 100ml,https://www.lookfantastic.com/clinique-for-men...,Moisturiser,"Water\Aqua\Eau, Squalane, Glycerin, Isostearyl...",£32.50
907,Sanctuary Spa Complexion Perfecting Radiance M...,https://www.lookfantastic.com/sanctuary-spa-co...,Exfoliator,"Glycerin, Aqua (Water), PEG-60 Hydrogenated Ca...",£2.99

In [11]:
# types de données
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1138 entries, 0 to 1137
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_name  1138 non-null   str
 1   product_url   1138 non-null   str
 2   product_type  1138 non-null   str
 3   ingredients   1138 non-null   str
 4   price         1138 non-null   str
dtypes: str(5)
memory usage: 44.6 KB

In [10]:
df.describe(include="all")

,product_name,product_url,product_type,ingredients,price
count,1138,1138,1138,1138,1138
unique,1138,1126,14,1090,290
top,The Ordinary Natural Moisturising Factors + HA...,https://www.lookfantastic.com/lancome-advanced...,Mask,"Purified Water, Glycerin, Ceteareth-20 and Cet...",£22.00
freq,1,4,124,4,33

In [7]:
# nombre de valeurs manquantes
df.isna().sum()

product_name    0
product_url     0
product_type    0
ingredients     0
price           0
dtype: int64

### En résumé, ce dataset est riche et exploitable, mais il ne comporte pas d'informations directes qui répondent aux problématiques d'acné par exemple.
### Il faudra pour cela faire du prétraitement.

# Nettoyage des données

### Traitement préalable pour le RAG pour la problématique d'acné

In [30]:
def generate_description(row):
    text = row["ingredients"].lower()
    
    desc = "This product is used for "

    if "salicylic" in text:
        desc += "treating acne and unclogging pores, "
    if "hyaluronic" in text:
        desc += "hydration, "
    if "retinol" in text:
        desc += "anti-aging and skin renewal, "
    if "niacinamide" in text:
        desc += "reducing inflammation and oil control, "

    return desc.strip(", ")

df["generated_description"] = df.apply(generate_description, axis=1)

In [31]:
df

,product_name,product_url,product_type,ingredients,price,generated_description
0,The Ordinary Natural Moisturising Factors + HA...,https://www.lookfantastic.com/the-ordinary-nat...,Moisturiser,"Aqua (Water), Caprylic/Capric Triglyceride, Ce...",£5.20,This product is used for
1,CeraVe Facial Moisturising Lotion SPF 25 52ml,https://www.lookfantastic.com/cerave-facial-mo...,Moisturiser,"Aqua/Water, Homosalate, Glycerin, Octocrylene,...",£13.00,This product is used for reducing inflammation...
2,The Ordinary Hyaluronic Acid 2% + B5 Hydration...,https://www.lookfantastic.com/the-ordinary-hya...,Moisturiser,"Aqua (Water), Sodium Hyaluronate, Sodium Hyalu...",£6.20,This product is used for
3,AMELIORATE Transforming Body Lotion 200ml,https://www.lookfantastic.com/ameliorate-trans...,Moisturiser,"Aqua/Water/Eau, Ammonium Lactate, C12-15 Alkyl...",£22.50,This product is used for
4,CeraVe Moisturising Cream 454g,https://www.lookfantastic.com/cerave-moisturis...,Moisturiser,"Purified Water, Glycerin, Ceteareth-20 and Cet...",£16.00,This product is used for hydration
...,...,...,...,...,...,...
1133,Elemis Life Elixirs Embrace Bath and Shower El...,https://www.lookfantastic.com/elemis-life-elix...,Bath Oil,"Prunus Amygdalus Dulcis (Sweet Almond) Oil, TI...",£55.00,This product is used for
1134,Love Boo Splendidly Soothing Bath Soak (250ml),https://www.lookfantastic.com/love-boo-splendi...,Bath Oil,"Aqua, sodium lauroyl sarcosinate, sodium cocoa...",£10.99,This product is used for
1135,Elemis Life Elixirs Fortitude Bath and Shower ...,https://www.lookfantastic.com/elemis-life-elix...,Bath Oil,"Prunus Amygdalus Dulcis (Sweet Almond) Oil, TI...",£55.00,This product is used for
1136,Connock London Kukui Oil Soothing Bath & Showe...,https://www.lookfantastic.com/connock-london-k...,Bath Oil,"Caprylic/Capric Triglyceride, PEG-40 Sorbitan ...",£36.00,This product is used for
1137,Weleda Baby Calendula Cream Bath (200ml),https://www.lookfantastic.com/weleda-baby-cale...,Bath Oil,"Water (Aqua), Prunis Amygdalus Dulcis (Sweet A...",£13.95,This product is used for

In [36]:
df.to_csv("lookfantastic_skincare_cleaned.csv", index=False)

In [ ]:
s